on: [push]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout code
     
    - name: Setup MSBuild path
      uses: warrenbuckley/Setup-MSBuild@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet packages
      run: nuget restore EntwineLLM.sln
 
    - name: Build EntwineLLM
      run: msbuild EntwineLLM.sln /p:Configuration=Release